export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";
export const DELETE_ACCOUNT = "DELETE_ACCOUNT";
export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";

//Services

//Women
export const GET_ALL_WOMEN_SERVICES_SUCCESS = "GET_ALL_WOMEN_SERVICES_SUCCESS";
export const GET_ALL_WOMEN_SERVICES_ERROR = "GET_ALL_WOMEN_SERVICES_ERROR";
export const GET_WOMEN_SERVICE_SUCCESS = "GET_WOMEN_SERVICE_SUCCESS";
export const GET_WOMEN_SERVICE_ERROR = "GET_WOMEN_SERVICE_ERROR";

//Men
export const GET_ALL_MEN_SERVICES_SUCCESS = "GET_ALL_MEN_SERVICES_SUCCESS";
export const GET_ALL_MEN_SERVICES_ERROR = "GET_ALL_MEN_SERVICES_ERROR";
export const GET_MEN_SERVICE_SUCCESS = "GET_MEN_SERVICE_SUCCESS";
export const GET_MEN_SERVICE_ERROR = "GET_MEN_SERVICE_ERROR";

//Kid
export const GET_ALL_KID_SERVICES_SUCCESS = "GET_ALL_KID_SERVICES_SUCCESS";
export const GET_ALL_KID_SERVICES_ERROR = "GET_ALL_KID_SERVICES_ERROR";
export const GET_KID_SERVICE_SUCCESS = "GET_KID_SERVICE_SUCCESS";
export const GET_KID_SERVICE_ERROR = "GET_KID_SERVICE_ERROR";
